### PR TITLE
Update LangFiles service , Added orginal file name

### PR DESCRIPTION
**Pull request by abdelrahmanahmed**
Reference #48 .
**Original name** is the name that is stored in the project directory , now the file name with underscore can be viewed without any problem .

### CODE REVIEW

**Review by abdelrahmanahmed — COMMENTED** [review]
i added it by mistake , it should be in a new pull request

**Comment by abdelrahmanahmed** [comment]
@lloy0076 any news?

**Comment by lloy0076** [comment]
Just out of morbid interest, why would we want to use 'original_name'?

**Comment by abdelrahmanahmed** [comment]
@lloy0076 
### What i want to do:
I have a translation file name that contains underscore (example_1.php) , and i don't  want view this underscore in the tab (more readable) like the following screenshot.
What i tried to do
**original_name :** is used to link to the file translation (in the href attribute )
**name** : is used to view the file name without underscore .
image

I don't know why you are removing underscore from file name so i suggested to add another key so we can use both underscored (for link ) and without underscore  for view.

**Comment by lloy0076** [comment]
So the **actual** problem is the way the system creates the name(s) for fields?

**Comment by abdelrahmanahmed** [comment]
@lloy0076  that's correct

**Comment by lloy0076** [comment]
Would https://github.com/Laravel-Backpack/CRUD/pull/688 fix it?

**Comment by abdelrahmanahmed** [comment]
@lloy0076 unfortunately no, it will not solve the translation files name

**Comment by tabacitu** [comment]
I see no harm in this. Merged!

**Pull request merged**
