### PR TITLE
Enabled custom routing

### PR DESCRIPTION
**Pull request by eduardoarandah**
related to this pull request
Laravel-Backpack/Base#156

### CODE REVIEW

**Comment by lloy0076** [comment]
https://github.com/Laravel-Backpack/Base/issues/131 will also address this...

**Comment by lloy0076** [comment]
@tabacitu - is this one meant to have customizable route files? I forget if that's one huge PR or in each single Backpack sub-repository thingo...

**Comment by tabacitu** [comment]
@lloy0076 - it's supposed to be a PR for each package. Seems like I missed this one, so it needs to be done :-) Will submit an issue for it so we don't forget.

@eduardoarandah - I think the "extend the routes" procedure we used in all other backpack packages is a more uniform solution - let's go with that one.

Cheers!

**Comment by lloy0076** [comment]
@tabacitu - what's up with this?

**Review by lloy0076 — APPROVED** [review]
On the basis that I can't really see how this can break anything I'm going to throw this to a big green tick!

**Comment by tabacitu** [comment]
Hi guys,

I think is no longer the "default" way to load routes, so I'm going to close this PR without merging it. In my opinion, this should have a separate routes file that can be overwritten, just like all other packages.

Cheers!

**Pull request closed without merging**
