### PR TITLE
Fix output code style (Fixes #28)

### LINKED ISSUE #28: Saved file should be formatted to coding standard
The language files saved by LangFileManager has these styling problems:

1. The return statement is indented by one space. Should be no space.
2. The strings are enclosed with "double quotes", should be 'single quotes'.
3. The array of elements must have the last element also with a trailing comma. 
4. The file is missing a final newline.

### PR DESCRIPTION
**Pull request by yusufkandemir**
This PR aims to fix #28

 **Changes**
- Added trailing comma to arrays.
- Added a new line at end of file.
- Changed double quotes to single quotes.
- Changed booleans from uppercase to lowercase.
- Removed extra space after php tag, extra space before return.
- Changed detection of number indexed elements from array-based to element-based.

### CODE REVIEW

**Review by tabacitu — APPROVED** [review]
Looks good to me!

**Comment by tabacitu** [comment]
Wow - thank you @yusufkandemir - sounds a lot better to me. 

@AlinGhitu this is your baby - what do you think?

**Comment by Ghitu** [comment]
@tabacitu We should merge it.

**Comment by AbbyJanke** [comment]
@tabacitu Been here for awhile, but I just tested it on 4.1 and has no issues. Any chance of getting it merged?

**Comment by tabacitu** [comment]
Wow - indeed this has been waiting for quite some time now. Sorry for taking so long @yusufkandemir , @Ghitu and @AbbyJanke . Thanks a lot for confirming it works well @AbbyJanke , merging and tagging right now! Let me know if you encounter any issues.

PS. I don't use this package very often - if at all. So if anybody else wants to maintain it, I'm more than happy to give the reigns over, so it gets the attention it deserves. Alternatively, if anybody creates a better package (read - one that actually stores the lang strings in the db, then caches them, instead of actually modifying files in production - like suggested in https://github.com/Laravel-Backpack/LangFileManager/issues/3), then I'd be more than happy to deprecate this package and forward everybody to use the new one.

**Pull request merged**
